spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: melck
    password: melck123
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
