server:
  port: 8089

spring:
  profiles:
    active: ${APP_PROFILE:test}

  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS:mck.enterprises.clinic@gmail.com}
    password: ${EMAIL_PASSWORD:hlqczlrjdjfxzykn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          wrhitetimeout: 5000
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

