version: '3.7'
services:
  
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: melck
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: product
    volumes:
      - ./product-db:/var/lib/postgresql/data

  api-gateway:
    image: melquisedequejr/mck-ecommerce-api-gateway:1.0
    container_name: api-gateway
    ports:
      - '8080:8080'
    environment:
      - APP_PROFILE=docker
    depends_on:
      - discovery-server
      - keycloak
      - product-service
      - reviews-service
    networks:
      - mck-net
    restart: always

  discovery-server:
    image: melquisedequejr/mck-ecommerce-discovery-server:1.0
    container_name: discovery-server
    ports:
      - '8761:8761'
    networks:
      - mck-net
    restart: always

  product-service:
    image: melquisedequejr/mck-ecommerce-product-service:1.0
    container_name: product-service
    ports:
      - '8083:8083'
    restart: always
    environment:
      - APP_PROFILE=docker
    depends_on:
      - discovery-server
      - rabbitmq
      - redis
      - db
    networks:
      - mck-net

  reviews-service:
    image: melquisedequejr/mck-ecommerce-review-service:1.0
    container_name: review-service
    environment:
      - APP_PROFILE=docker
    ports:
      - '8084:8084'
    restart: always
    depends_on:
      - rabbitmq
      - discovery-server
      - db
    networks:
      - mck-net

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      - mck-net

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mck-net

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    container_name: keycloak
    ports:
      - 8088:8080
    hostname: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - mck-net
    volumes:
      - ./realms/:/opt/keycloak/data/import
    command: [ "start-dev", "--import-realm" ]

networks:
  mck-net: 
    
   