version: '3.7'
services:
  
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: melck
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: product
    volumes:
      - ./product-db:/var/lib/postgresql/data

  api-gateway:
    image: melquisedequejr/mck-ecommerce-api-gateway:1.0
    container_name: api-gateway
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - eureka-discovery-server
      - keycloak
      - product-service
      - reviews-service

  eureka-discovery-server:
    image: melquisedequejr/mck-ecommerce-eureka-discovery-server:1.0
    ports:
      - '8761:8761'

  product-service:
    image: melquisedequejr/mck-ecommerce-product-service:1.0
    container_name: product-service
    ports:
      - '8083:8083'
    restart: always
    depends_on:
      - eureka-discovery-server
      - rabbitmq
      - redis
      - db

  reviews-service:
    image: melquisedequejr/mck-ecommerce-review-service:1.0
    container_name: review-service
    ports:
      - '8084:8084'
    restart: always
    depends_on:
      - rabbitmq
      - eureka-discovery-server
      - db
      
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    ports:
#      - "8090:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    command: [ "start-dev" ]
    ports:
      - 8088:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

