server:
  port: 8087
spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: auth-server

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          oauth2-client-credentials:
            client-id: auth-client
            client-secret: znXMMSyZ72pm1XGbrvnSxTUJlGWiKhDV
            scope: openid, profile, roles
            authorization-grant-type: password
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/mck-e-commerce
            token-uri: http://localhost:8088/realms/mck-e-commerce/protocol/openid-connect/token
            logout-uri: http://localhost:8088/realms/mck-e-commerce/protocol/openid-connect/logout
            introspect-uri: http://localhost:8088/realms/mck-e-commerce/protocol/openid-connect/token/introspect

keycloak:
  realm: mck-e-commerce
  resource: auth-client
  auth-server-url: http://localhost:8088
  ssl-required: external
  use-resource-role-mappings: true
  credentials:
    secret: znXMMSyZ72pm1XGbrvnSxTUJlGWiKhDV
  public-client: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
