server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8088/realms/mck-e-commerce}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
           issuer-uri: ${ISSUER_URI:http://localhost:8088/realms/mck-e-commerce}
           user-name-attribute: preferred_username
        registration:
          spring-cloud-gateway-client:
              client-id: ${CLIENT_ID:mck-e-commerce-backend}
              client-secret: ${CLIENT_SECRET:7EeNrGlUXUgJZBx5dgPu9X9w4lMKYyAd}
              provider: keycloak
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/spring-cloud-gateway-client
              scope: openid

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_LAST
        - TokenRelay=
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
      routes:
# Product Service Route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
            - Method=GET,POST,PUT,PATCH,DELETE
# Cart Service Route
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
            - Method=GET,POST,PUT,PATCH,DELETE
# User Service Route
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
            - Method=GET,POST,PUT,PATCH,DELETE
# Review Service Route
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/v1/reviews/**
            - Method=GET,POST,PUT,PATCH,DELETE
# Order Service Route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
            - Method=GET,POST,PUT,PATCH,DELETE

# Inventory Service Route
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory/**
            - Method=GET,POST,PUT,PATCH,DELETE
# Notification Service Route
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
            - Method=GET,POST,PUT,PATCH,DELETE

# Discovery Service Route
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
# Discovery Service static resources Route
        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              routeDefinitionLocator: INFO
        security: DEBUG
