server:
  port: 8084
spring:
  application:
    name: review-service

app-config:
  client:
    product: ${PRODUCT_URI:http://localhost:8080/api/v1/products/%s}
    user: ${USER_URI:http://localhost:8080/api/v1/users/%s}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
