spring:
  datasource:
    url: jdbc:postgresql://db:5432/product
    username: melck
    password: 12345
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-server:8761/eureka
  instance:
    hostname: eureka-discovery-server
    
keycloak:
  realm: mck-e-commerce
  auth-server-url: http://keycloak:8088/auth
  ssl-required: external
  resource: spring-cloud-gateway-client

jwt:
  auth:
    converter:
      resource-id: spring-cloud-gateway-client
      principal-attribute: preferred_username