server:
  port: 8084
spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: review-service
  
  jpa:
    open-in-view: false
    
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mck-e-commerce
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  realm: mck-e-commerce
  auth-server-url: http://localhost:8088/auth
  ssl-required: external
  resource: spring-cloud-gateway-client

jwt:
  auth:
    converter:
      resource-id: spring-cloud-gateway-client
      principal-attribute: preferred_username

app-config:
  client:
    product: ${PRODUCT_URI:http://localhost:8083/api/v1/products/%s}
    user: ${USER_URI:http://localhost:8082/api/v1/users/%s}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    user:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slidingWindowType: COUNT_BASED
      automaticTransitionFromOpenToHalfOpenEnabled: true

    product:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slidingWindowType: COUNT_BASED
      automaticTransitionFromOpenToHalfOpenEnabled: true