server:
  port: 8083
spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: product-service

  jpa:
    open-in-view: false

  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 20S
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mck-e-commerce
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: spring-cloud-gateway-client
      principal-attribute: preferred_username

app-config:
  client:
    review: ${REVIEW_URI:http://localhost:8080/api/v1/reviews/%s}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
    instances:
      review:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        automaticTransitionFromOpenToHalfOpenEnabled: true

