server:
  port: 8083
spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: product-service
  jpa:
    open-in-view: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

