spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: melck
    password: 12345
    driver: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create-drop
