server:
  port: 8083
spring:
  profiles:
    active: ${APP_PROFILE:test}
  application:
    name: product-service
  jpa:
    open-in-view: false
app-config:
  client:
    review: ${REVIEW_URI:http://localhost:8080/api/v1/reviews/%s}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

resilience4j.circuitbreaker:
    instances:
      review:
        minimumNumberOfCalls: 3
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true