server:
  port: 8081

spring:
  profiles:
    active: ${APP_PROFILE:test}

  application:
    name: cart-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mck-e-commerce
          client-id: ${CLIENT_ID:spring-cloud-gateway-client}
          client-secret: ${CLIENT_SECRET:YoTjR7kxORsRjmBpL3siPBzBp7NQfxHV}

jwt:
  auth:
    converter:
      resource-id: spring-cloud-gateway-client
      principal-attribute: preferred_username

keycloak-client-id: ${CLIENT_ID:spring-cloud-gateway-client}
keycloak-client-secret: ${CLIENT_SECRET:YoTjR7kxORsRjmBpL3siPBzBp7NQfxHV}
keycloak-token-uri: localhost:8088/realms/mck-e-commerce/protocol/openid-connect/token

app-config:
  client:
    product: ${PRODUCT_URI:http://localhost:8080/api/v1/products/%s}
    product-cart: ${PRODUCT_CART_URI:http://localhost:8080/api/v1/products/cart}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    product:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      slidingWindowType: COUNT_BASED
      automaticTransitionFromOpenToHalfOpenEnabled: true



